version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /deploy/jong-poi
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /deploy/gateway
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
